<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11893" started-at="2019-01-30T13:46:52Z" finished-at="2019-01-30T13:47:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11893" started-at="2019-01-30T13:46:52Z" finished-at="2019-01-30T13:47:04Z">
      <class name="com.exampleActiTime.testCase.Verify_ErrorMessage">
        <test-method status="PASS" signature="testErrorMessage()[pri:0, instance:com.exampleActiTime.testCase.Verify_ErrorMessage@4cc0edeb]" name="testErrorMessage" duration-ms="11838" started-at="2019-01-30T13:46:52Z" finished-at="2019-01-30T13:47:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testErrorMessage -->
      </class> <!-- com.exampleActiTime.testCase.Verify_ErrorMessage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
